<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PluginFramework\PluginFramework.csproj" />
    <ProjectReference Include="..\Plugin1\Plugin1.csproj" />
    <ProjectReference Include="..\Plugin2\Plugin2.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
